# Site settings
title: Scylla Docs
email: info@scylladb.com
description: > # this means to ignore newlines until "baseurl:"
  Scylla is a Cassandra-compatible NoSQL data store that can handle 1 million transactions per second on a single server.

# To preview on GitHub Pages before the DNS cuts over
# baseurl: "/new-company-site" # the subpath of your site, e.g. /blog/

# Final location
baseurl: "" # the subpath of your site, e.g. /blog/

# url: "http://localhost" # the base hostname & protocol for your site
twitter_username: ScyllaDB
github_username: ScyllaDB
author: Scylla Community

gems: 
 - jekyll-sitemap
 - jekyll-redirect-from

# Build settings
markdown: kramdown

permalink: pretty

kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..2
