name: "Theme / Unit tests"

on:
  pull_request:
    branches:
      - master
    paths:
      - "sphinx_scylladb_theme/**"
  push:
    branches:
      - master
    paths:
      - "sphinx_scylladb_theme/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up env
        run: |
          make -C docs setupenv
          uv sync

      - name: Run tests
        run: uv run pytest .
